---
spring:
  security:
      user:
        name: admin
        password: 123456
  application:
    name: test-spring-cloud-eureka
  profiles: eureka-profile1
server:
  port: 5701
eureka:
  instance:
    hostname: test-eureka-yingke1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123456@test-eureka-yingke2:5702/eureka/
    register-with-eureka: true
    fetch-registry: true

---
spring:
  security:
      user:
        name: admin
        password: 123456
  application:
    name: test-spring-cloud-eureka
  profiles: eureka-profile2
server:
  port: 5702
eureka:
  instance:
    hostname: test-eureka-yingke2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123456@test-eureka-yingke1:5701/eureka/
    register-with-eureka: true
    fetch-registry: true